### ISSUE TITLE
Adding login modal 

### ISSUE THREAD

**Issue by as1733** [as1733/RentManagementSystem#3]
the home page should have a login button  on the navbar and pressing should present the login dialog box .

Acceptance - clicking the button / <a> tag  on the nav bar should make the dialog appear

**Comment by jma26** [comment]
Hey! Do you have a figma or PSD we can reference? Would this be plain CSS or with a library like Bootstrap, Material-UI etc.?

**Comment by as1733** [comment]
It can be any thing but it should be easily integrated and should  have seamless transition and responsive in nature

**Comment by jma26** [comment]
Okay, I'll take this issue on then!
