### ISSUE TITLE
Creating a 404 Page for all routes which are not defined in the react-router

### ISSUE THREAD

**Issue by as1733** [as1733/RentManagementSystem#35]

**Comment by AnimeshMore** [comment]
I would like to work on this issue.

**Comment by AnimeshMore** [comment]
I have created 404 Error Page. Please have a look on it and do let me know if there are any changes required before creating the PR.


![rent 1](https://user-images.githubusercontent.com/76648444/138439738-49155eb9-4bd9-4dc8-b6ff-f7af0aff19d8.jpg)


![rent 2](https://user-images.githubusercontent.com/76648444/138439744-08b14d84-b211-498b-b00e-ee83c8d6ddd2.jpg)

**Comment by as1733** [comment]
please create a pr , it looks fine to me
