### ISSUE TITLE
adding a new page - About us 

### ISSUE THREAD

**Issue by as1733** [as1733/RentManagementSystem#7]
A new page with about us should open when a user clicks the "about us" Button on the navigation bar ,

The page can be made using plain css / bootstrap / material ui . 
Please ensure that color scheme is matching to the homepage , 
the page can contain 
* social media links 
* A form to send the query 
* A short description 
*  Images(maybe)

**Comment by suprabhat25** [comment]
Can you assign me this issue?

**Comment by as1733** [comment]
I have assigned the issue to you @suprabhat25
